# Generated by Django 4.2.4 on 2023-08-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_resume_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.TextField(),
        ),
    ]
