# Generated by Django 4.2.4 on 2023-08-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_resume_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='social',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
